// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  heading: dynamic(() => import("./Heading")),
  link_description: dynamic(() => import("./LinkDescription")),
  text_block: dynamic(() => import("./TextBlock")),
};
